"""empty message

Revision ID: 1e614a20fff9
Revises: 532413826f8d
Create Date: 2025-03-01 19:39:33.124362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1e614a20fff9'
down_revision: Union[str, None] = '532413826f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusterresourcesnapshot',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cluster_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_cpu', sa.Integer(), nullable=False),
    sa.Column('total_ram', sa.Integer(), nullable=False),
    sa.Column('total_gpu', sa.Integer(), nullable=False),
    sa.Column('used_cpu', sa.Integer(), nullable=False),
    sa.Column('used_ram', sa.Integer(), nullable=False),
    sa.Column('used_gpu', sa.Integer(), nullable=False),
    sa.Column('available_cpu', sa.Integer(), nullable=False),
    sa.Column('available_ram', sa.Integer(), nullable=False),
    sa.Column('available_gpu', sa.Integer(), nullable=False),
    sa.Column('cpu_utilization', sa.Float(), nullable=False),
    sa.Column('ram_utilization', sa.Float(), nullable=False),
    sa.Column('gpu_utilization', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clusterresourcesnapshot')
    # ### end Alembic commands ###
