"""empty message

Revision ID: 47fe3518f455
Revises: 70ff8d14968e
Create Date: 2025-03-01 14:52:24.968078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '47fe3518f455'
down_revision: Union[str, None] = '70ff8d14968e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment', sa.Column('docker_image', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployment', 'docker_image')
    # ### end Alembic commands ###
